# ==========================================================================
# CRE WORKFLOW SETTINGS FILE — CRE-2: Trading Anomaly Detection
# ==========================================================================
# Workflow 2: TradeGuard — Detects suspicious betting patterns on-chain.
# Trigger  : Log Trigger — BetPlaced(uint256 marketId, address bettor, bool isYes, uint256 amount)
# Actions  : EVM Read (getMarket), Confidential HTTP x2 (NewsAPI + Groq),
#            Consensus, EVM Write (reportManipulation)

# ==========================================================================
staging-settings:
  user-workflow:
    workflow-name: "cre-2-tradeguard-staging"
  workflow-artifacts:
    workflow-path: "./main.ts"
    config-path: "./config.staging.json"
    secrets-path: "../secrets.yaml"


# ==========================================================================
production-settings:
  user-workflow:
    workflow-name: "cre-2-tradeguard-production"
  workflow-artifacts:
    workflow-path: "./main.ts"
    config-path: "./config.production.json"
    secrets-path: "../secrets.yaml"